title: ""
description: ""

baseurl: ""
url: "https://tburakarslan.github.io"

include:
  - googledd079750171f02c4.html
  - sitemap.xml

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
